#!/usr/bin/env bash
# vim: set filetype=sh:

# neovim
export EDITOR='nvim';

# for brew
export PATH="/usr/local/sbin:$PATH"

#Export Variables
export PATH=$HOME/dev_thunder/script:$HOME/bin:$PATH;

#for python
export PATH="/usr/local/opt/python@2/bin:$PATH"

# github
export HOMEBREW_GITHUB_API_TOKEN="021f916b34aff5765aa9870664b5af5475128852"

# for go
export GOPATH=/Users/levi/go
export PATH=$PATH:/usr/local/opt/go/libexec/bin:$GOPATH/bin
export GO15VENDOREXPERIMENT=1

# xunlei
export SL_ENV="DEV"
export TEST_URL="http://0.0.0.0:8080"

# anaconda 2
#export PATH="$PATH":~/anaconda2/bin

# for anaconda
#export PATH=/usr/local/anaconda3/bin:"$PATH"
#export PATH=~/anaconda2/bin:"$PATH"
#export PATH

