#!/usr/bin/env bash

function setproxy() {
    export ALL_PROXY=socks5://127.0.0.1:1086
}

function unsetproxy() {
    unset ALL_PROXY
}

function settx() {
    export http_proxy="http://web-proxy.tencent.com:8080";
    export https_proxy="http://web-proxy.tencent.com:8080";
    export no_proxy="git.code.oa.com,r.tnpm.oa.com,*.mnet2.com";
}

function unsettx() {
    unset http_proxy;
    unset https_proxy;
    unset no_proxy;
}


# Syntax-highlight JSON strings or files,similar to json format
# Usage: `json '{"foo":42}'` or `echo '{"foo":42}' | json`
function json() {
    if [ -t 0 ]; then # argument
        python -mjson.tool <<< "$*" | pygmentize -l javascript;
    else # pipe
        python -mjson.tool | pygmentize -l javascript;
    fi;
}
