#!/usr/bin/env bash

function setproxy() {
    export ALL_PROXY=socks5://127.0.0.1:1080
}

function unsetproxy() {
    unset ALL_PROXY
}


# Syntax-highlight JSON strings or files,similar to json format
# Usage: `json '{"foo":42}'` or `echo '{"foo":42}' | json`
function json() {
    if [ -t 0 ]; then # argument
        python -mjson.tool <<< "$*" | pygmentize -l javascript;
    else # pipe
        python -mjson.tool | pygmentize -l javascript;
    fi;
}
